// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLz6DjcCsPNVri5YR6uNYpiOy9rBUekDY',
    appId: '1:929417018358:web:3e455248f7e741f91525d7',
    messagingSenderId: '929417018358',
    projectId: 'flutter-test-deb2e',
    authDomain: 'flutter-test-deb2e.firebaseapp.com',
    storageBucket: 'flutter-test-deb2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVRYRpvAOoesPzrFFaem0S7AeC0LqESxg',
    appId: '1:929417018358:android:5c950a02dc3915a01525d7',
    messagingSenderId: '929417018358',
    projectId: 'flutter-test-deb2e',
    storageBucket: 'flutter-test-deb2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCanLWNqjxFXeDhCyjsQ-B2FDw-NJhlKSY',
    appId: '1:929417018358:ios:24fc2c7c413855ff1525d7',
    messagingSenderId: '929417018358',
    projectId: 'flutter-test-deb2e',
    storageBucket: 'flutter-test-deb2e.appspot.com',
    iosBundleId: 'com.harrisonolvera.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCanLWNqjxFXeDhCyjsQ-B2FDw-NJhlKSY',
    appId: '1:929417018358:ios:c693b0dcd36b3aa41525d7',
    messagingSenderId: '929417018358',
    projectId: 'flutter-test-deb2e',
    storageBucket: 'flutter-test-deb2e.appspot.com',
    iosBundleId: 'com.harrisonolvera.crudFirebase.RunnerTests',
  );
}
